# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZoomPreviewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZoomPreviewDemo
  pod 'ImageZoomViewPW', :git => 'https://github.com/pierre-wehbe/ImageZoomViewPW.git', :tag => '1.0.3'

end
